name: Package Build Issues
description: "Report an issue that occurs when building a package"
title: "[PACKAGE ISSUE]: Add brief description here"
labels:
  [
    "element: package :gift:",
    "status: new :phone:",
    "priority: CRITICAL :clock1:",
    "wait: triage :hospital:",
  ]
assignees:
  - rossclarkartist
body:
  - type: markdown
    attributes:
      value: _**Assistance is available for using this form.  See [reporting an issue with a package](https://archiv8.github.io/support/issues/package-issue) on the Archiv8 website**_. Opening this link in a new tab or window is recommended to prevent losing any data from this form
  - type: input
    id: package-name
    attributes:
      label: Package effected by the issue
      description: Give the full name of the package
      placeholder: pacman
    validations:
        required: true
