name: Form Suggestion
description: "Help Archiv8 to improve its relationship with users by suggesting an improvement for a form"
title: "[Form Suggestion]: "
labels:
  [
    "element: form :scroll:",
    "status: new :ear:",
    "type: request :open_hands:",
    "priority: LOW :ok_hand:",
    "wait: triage :hospital:",
  ]
assignees:
  - rossclarkartist
body:
  - type: markdown
    attributes:
      value: "_**Thanks for taking the time to to suggest  making an improvement to a form.  For assistance read the instructions on [submitting an improvement](https://archiv8.github.io/reporting-issues/form-suggestion)**_"
  - type: markdown
    attributes:
      value: "# Basic Facts"
  - type: markdown
    attributes:
      value: "_**The following information is important when triaging the issue**_"
  - type: markdown
    attributes:
      value: "## What browser was being used?"
  - type: markdown
    attributes:
      value: "_This information may help in discovering the issue as there are differences in the way web browsers render HTML, CSS and JavaScript etc_"
  - type: checkboxes
    id: browser
    attributes:
      label: The Web Browser
      description: "Name of the web browser being used:"
      options:
        - label: Chrome (Google)
          required: false
        - label: Chromium
          required: false
        - label: Edge (Microsoft)
          required: false
        - label: ELinks
          required: false
        - label: Firefox (Mozilla)
          required: false
        - label: IE (Microsoft)
          required: false
        - label: Opera
          required: false
        - label: Safari (Apple)
          required: false
  - type: input
    id: other-browser
    attributes:
      label: Other Browser
      description: "If the browser wasn't listed above enter it's name in the box below:"
      placeholder: "Alternate Browser Name"
    validations:
      required: false
  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: "The version of the browser using semantic versioning, where available"
      placeholder: "10.9.1"
    validations:
      required: false
  - type: markdown
    attributes:
      value: "# Describe you suggestion below"
  - type: textarea
    id: suggestion
    attributes:
      label: Your suggestion
      description: "What could be improved:"
      placeholder: "Please give as much information as possible.  Using a bulleted list will help improve readability by breaking down the list into component parts."
      render: text
  - type: markdown
    attributes:
      value: "# Fixing the issue"
  - type: textarea
    id: issue-fix
    attributes:
      label: Changes
      description: "Help Archiv8 by providing a way to make the suggested change if you are able. Creating a pul request is the best way to achieve this."
      render: text
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: "The code of conduct and related documents are intended to encourage and grow a healthy community:"
      options:
        - label: By submitting this issue I am agreeing to follow Archiv8's [Code of Conduct](https://archiv8.github.io/community/code-of-conduct) and other [community guidelines](https://archiv8.github.io/community)
          required: true
  - type: markdown
    attributes:
      value: "_**Is there a problem with this form?  Use CTRL+click on the appropriate link below and open a form in a new browser browser tab**_"
  - type: markdown
    attributes:
      value: "[Report an issue with this form](https://github.com/Archiv8/play/issues/new?assignees=rossclarkartist&labels=element%3A+form+%3Ascroll%3A%2Cstatus%3A+new+%3Aear%3A%2Cpriority%3A+NORMAL+%3Acalendar%3A%2Cwait%3A+triage+%3Ahospital%3A+&template=FORM_FORM-ISSUE.yml&title=%5BForm+Issue%5D%3A+Issue+with+suggestion+form+) or [suggest an improvement](https://github.com/Archiv8/play/issues/new?assignees=rossclarkartist&labels=element%3A+form+%3Ascroll%3A%2Cstatus%3A+new+%3Aear%3A%2Cpriority%3A+LOW+%3Aok_hand%3A%2Cwait%3A+triage+%3Ahospital%3A+&template=FORM_FORM-SUGGESTION.yml&title=%5BForm+Suggestion%5D%3A+Improvement+to+suggestion+form+)"
  - type: markdown
    attributes:
      value: "(c) Ross Clark and Archiv8 2021 - 2022"
  - type: markdown
    attributes:
      value: "This form is released under the Creative Commons Attribution-ShareAlike 4.0 International License."
