name: Package Build Issues
description: "Report an issue that occurs when building a package"
title: "[PACKAGE ISSUE]: Add brief description here"
labels:
  [
    "element: package :gift:",
    "status: new :phone:",
    "priority: CRITICAL :clock1:",
    "wait: triage :hospital:",
  ]
assignees:
  - rossclarkartist
body:
  - type: markdown
    attributes:
      value: _**Assistance is available for using this form.  See [reporting an issue with a package](https://archiv8.github.io/support/issues/package-issue) on the Archiv8 website**_. Opening this link in a new tab or window is recommended to prevent losing any data from this form
  - type: input
    id: package-name
    attributes:
      label: Package effected by the issue
      description: Give the full name of the package
      placeholder: pacman
    validations:
        required: true
  - type: input
    id: package-version
    attributes:
      label: The version of the package effected by the issue
      description: Give the full version number. For example, for aurutils-10b-1, the version number would be _**10b-1**_
      placeholder: 10b-1
    validations:
        required: true
  - type: checkboxes
    id: arch-updated
    attributes:
      label: Arch Linux
      description: Is Arch Linux Up To Date
      options:
        - label: "yes"
        - label: "no"
    validations:
      required: true
  - type: checkboxes
    id: package-updated
    attributes:
      label: Arch Linux
      description: Is the latest version of the package from the Archiv8 repository being built. If unsure go to https://github.com/Archiv8 then search for the appropriate repository.  Click on tags. Now check the version number of the downloaded package matches the top release on the page
      options:
        - label: "yes"
        - label: "no"
    validations:
      required: true
  - type: dropdown
    id: build-env
    attributes:
      label: How is the package being built?
      description: What method is being used to build the package?
      multiple: true
      options:
        - makepkg
        - aurutils
        - other clean chroot
        - other
    validations:
      required: true
  - type: textarea
    id: depends
    attributes:
      label: Dependencies
      description: How did you handle Archiv8 dependencies.  The recommended way is to place **only** the Archiv8 dependencies that are needed in a custom local repository.
      value: I used a ...
    validations:
      required: false
  - type: textarea
    id: further-info
    attributes:
      label: Further Information
      description: Is there more information that will be helpful. Please give as much information as possible.
      placeholder: Use of available formatting options is suggested.  For example, using a numbered list when describing the build process will improve triage and response times by separating the information into easily identifiable chunks
    validations:
      required: false
  - type: textarea
    id: fix
    attributes:
      label: Help fixing the issue
      description: Contributions are always welcome
      placeholder: Guidance is provided through the Archiv8 website at https://Archiv8.github.io/contributing.  Also https://docs.github.com/en/pull-requests has further information
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Community Guidelines
      description: The community guidelines are intended to encourage and grow a healthy community
      options:
        - label: By submitting this issue I am agreeing to follow Archiv8's [community guidelines](https://archiv8.github.io/community)
    validations:
      required: true
  - type: markdown
    attributes:
      value: "[Suggest An Improvement To This Form](https://github.com/Archiv8/.github/issues/new?assignees=rossclarkartist&labels=element%3A+form+%3Ascroll%3A%2Cstatus%3A+new+%3Aphone%3A%2Cpriority%3A+NORMAL+%3Acalendar%3A%2Cwait%3A+triage+%3Ahospital%3A&template=FORM_FORM.yml&title=%5BFORM%5D%3A+Improvement+for+FORM_PACKAGE_BUILD). _**Open the link in a new browser tab or window to prevent the loss of data**_"
  - type: markdown
    attributes:
      value: (c) Ross Clark and Archiv8 2021 - 2022
  - type: markdown
    attributes:
      value: This form is released under the Creative Commons Attribution-ShareAlike 4.0 International License
