name: Package Build Issues
description: "Report an issue that occurs when building a package"
title: "[PACKAGE ISSUE]: Add brief description here"
labels:
  [
    "element: package :gift:",
    "status: new :phone:",
    "priority: CRITICAL :clock1:",
    "wait: triage :hospital:",
  ]
assignees:
  - rossclarkartist
body:
  - type: markdown
    attributes:
      value: _**Assistance is available for using this form.  See [reporting an issue with a package](https://archiv8.github.io/support/issues/package-issue) on the Archiv8 website**_. Opening this link in a new tab or window is recommended to prevent losing any data from this form
  - type: input
    id: package-name
    attributes:
      label: Package effected by the issue
      description: Give the full name of the package
      placeholder: pacman
    validations:
        required: true
  - type: input
    id: package-version
    attributes:
      label: The version of the package effected by the issue
      description: Give the full version number
      placeholder: pacman
    validations:
        required: true
  - type: checkboxes
    id: arch-updated
    attributes:
      label: Arch Linux
      description: Is Arch Linux Up To Date
      options:
        - label: "yes"
        - label: "no"
    validations:
      required: true
  - type: checkboxes
    id: package-updated
    attributes:
      label: Arch Linux
      description: Is the latest version of the package from the Archiv8 repository being built. If unsure go to https://github.com/Archiv8 then find the appropriate repository.  Click on tags, then check the version number of the downloaded package matches the top release on the page
      options:
        - label: "yes"
        - label: "no"
    validations:
      required: true
  - type: dropdown
    id: build-env
    attributes:
      label: How is the package being built?
      description: What method is being used to build the package?
      options:
        - makepkg
        - other
    validations:
      required: true
