name: Upstream Reports
description: "Report an issue with upstream code or request an existing patch be applied. This form is not intended to be used in place of creating upstream issues"
title: "[UPSTREAM]: Add brief description here"
labels:
  [
    "element: src :speedboat:",
    "status: new :phone:",
    "priority: NORMAL :calendar:",
    "wait: triage :hospital:",
  ]
assignees:
  - rossclarkartist
body:
  - type: markdown
    attributes:
      value: "_**Assistance is available for using this form.  See the [reporting an issue with an upstream source](https://archiv8.github.io/support/issues/upstream-issue) on the Archiv8 website**_. Opening this link in a new tab or window is recommended to prevent losing any data from this form"
  - type: input
    id: package-name
    attributes:
      label: "What package does the upstream issue effect?"
      description: "Give the name of the package as provided by the upstream sources"
      placeholder: "netbeans"
  - type: input
    id: issue-link
    attributes:
      label: "Provide a link to the upstream issue"
      placeholder: "https://github.com/Archiv8/.github/issues/an-issue"
    validations:
      required: true
  - type: textarea
    id: further-info
    attributes:
      label: "Further Information"
      description: "Is there more information that will be helpful"
      placeholder: "Use of available formatting options is suggested.  For example, a numbered list when describing the build process will improve triage and response times by separating the information into easily identifiable chunks"
  - type: textarea
    id: fix
    attributes:
      label: "Fixing the issue"
      description: "Contributions are always welcome"
      placeholder: "Guidance is provided through the Archiv8 website at https://Archiv8.github.io/contributing.  Also https://docs.github.com/en/pull-requests has further information"
  - type: checkboxes
    id: terms
    attributes:
      label: "Community Guidelines"
      description: "The community guidelines are intended to encourage and grow a healthy community:"
      options:
        - label: "By submitting this issue I am agreeing to follow Archiv8's [community guidelines](https://archiv8.github.io/community)"
          required: true
  - type: markdown
    attributes:
      value: "[Suggest An Improvement To This Form](https://github.com/Archiv8/.github/issues/new?assignees=rossclarkartist&labels=element%3A+form+%3Ascroll%3A%2Cstatus%3A+new+%3Aphone%3A%2Cpriority%3A+NORMAL+%3Acalendar%3A%2Cwait%3A+triage+%3Ahospital%3A&template=FORM_OTHER.yml&title=%5BFORM%5D%3A+Improvement+for+FORM_UPSTREAM). _**Open the link in a new browser tab or window to prevent the loss of data**_"
  - type: markdown
    attributes:
      value: "(c) Ross Clark and Archiv8 2021 - 2023"
  - type: markdown
    attributes:
      value: "This form is released under the Creative Commons Attribution-ShareAlike 4.0 International License"
