name: Upstream Issue
description: Report an issue with the upstream source code.
body:
  - type: markdown
    attributes:
      value: "Read the policy regarding issues with upstream source code before using this form. The information entered will help with triaging the issue and give Archiv8 and, possibly the upstream authors a better chance a finding a fix."
  - type: markdown
    attributes:
      value: "Firstly, information about your system"
  - type: checkboxes
    attributes:
      label: About Your Hardware
      description: S.
      options:
        - label: This.
          required: true
  - type: checkboxes
    attributes:
      label: About Your Software
      description: This information will help in triaging the issue.
      options:
        - label: All packages running on my machine are up to date.
          required: true
        - label: I have read tht latest [Arch Linux news](https://archlinux.org/) and applied any relevent fixes suggested.
          required: true
  - type: textarea
    attributes:
      label: About The Issue
      description: The following information will help in triaging the issue.
      render: text
  - type: markdown
    attributes:
      value: "Community Co-operation"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow the policies as outlined by [Archiv8](https://example.com)
      options:
        - label: I agree to follow Archiv8's Code of Conduct
          required: true
        - label: I agree to follow Archiv8's Contributor Agreement
          required: true
        - label: I agree to follow Archiv8's Security Policy
          required: true
        - label: I agree to follow this Archiv8's Community Support Guidelines
          required: true
